# Generated by Django 2.0.4 on 2018-05-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0003_auto_20180513_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
